### ISSUE TITLE
On a volume with the maximum number of files/directories, bitsy bye will display the last directory twice

### ISSUE THREAD

**Issue by GSuser007** [ProDOS-8/ProDOS8-Testing#29]
## Description
When the directory is full, the last directory name will be listed twice.
![pd25a7_last_dir_twice.png](http://devokun.s3-website-us-east-1.amazonaws.com/pd25a7_last_dir_twice.png)

## Expected Behavior
Each directory should be listed once.

## Actual Behavior
Final directory is listed twice

![pd25a7_last_dir_twice.png](http://devokun.s3-website-us-east-1.amazonaws.com/pd25a7_last_dir_twice.png)

## Possible Fix
The for-loop(?) needs to not do the final/extra print.

## Steps to Reproduce
* Use either `GSPlus 0.13` or `VirtuApple II 9.2`
* Boot from **ProDOS 2.5a7**
* Copy the boot disk contents to a test disk.
* Use the CopyIIplus utils to create directories on the test disk until the directory is full.
* View the directory in **bitsy bye**

### The two disks used for testing are here:
* [PD25A7.po](http://devokun.s3-website-us-east-1.amazonaws.com/PD25A7.po)
* [PD25A7B.po](http://devokun.s3-website-us-east-1.amazonaws.com/PD25A7B.po)

## Context
When using bitsy bye, the final directory entry is listed twice.

## Your Environment
* Apple IIgs Emulator

### Hardware:
* Apple IIgs ROM01

### ProDOS8 version:
2.5a7

**Comment by JohnMBrooks** [comment]
I have not seen this problem. What steps did you take to cause it to happen?

**Comment by DevoKun** [comment]
Hello, @GSuser007 .
Thank you for submitting this issue.
I tried to reproduce the issue you are seeing using **GSPlus 0.13** on MacOS X using both the `3.5"` and `5.25"` drives and was unable to get the results that you do.
I _did_ see that the last directory in the list was listed **twice**.
However, that problem was not specific to the IIgs as I also saw it on the IIe.
![pd25a7_last_dir_twice.png](http://devokun.s3-website-us-east-1.amazonaws.com/pd25a7_last_dir_twice.png)

Please take a screenshot of what you are experiencing?

What IIgs emulator are you using?

How did you create the directories? Did you use BASIC, ProSel, CopyIIplus, or something else?

Thanks,

**Comment by JohnMBrooks** [comment]
If possible, please upload a disk image that demonstrates the duplicate file entry.

Thanks!

**Comment by DevoKun** [comment]
* [PD25A7.po](http://devokun.s3-website-us-east-1.amazonaws.com/PD25A7.po)
* [PD25A7B.po](http://devokun.s3-website-us-east-1.amazonaws.com/PD25A7B.po)

**Comment by JohnMBrooks** [comment]
Thanks guys. Fixed in alpha 8.
