### ISSUE TITLE
Documentation: include file date format

### ISSUE THREAD

**Issue by inexorabletash** [ProDOS-8/ProDOS8-Testing#42]
The documentation on https://prodos8.com/releases/prodos-25/ details the new 6-byte date/time format bits in the ProDOS global page, but not the 4-byte format used in directory entries/GET/SET_FILE_INFO for file creation/modification times.

**Comment by JohnMBrooks** [comment]
msec ($BF8E) and sec ($BF8F) are not stored in dir entries, and are optional since not all clock drivers support msec or sec.

The new-to-2.5 extended dir entry format is identical to the time/date bytes at $BF90-$BF93.

Noted that the 2.5 documentation should be amended to clarify that the last 4-byte time/date subset of the 6-byte global page time/date is what is stored in dir entries.

Thanks,
-JB

**Comment by inexorabletash** [comment]
Okay - sounds like the format has changed since the KansasFest presentation a few years ago. Sorry for the churn here.

**Comment by DevoKun** [comment]
* Documentation updated.
* [Pull request generated and merged](https://github.com/ProDOS-8/ProDOS-8.github.io/pull/30)
* Should be online soon.
