### ISSUE TITLE
File vs. Global date/time issue

### ISSUE THREAD

**Issue by inexorabletash** [ProDOS-8/ProDOS8-Testing#43]
In 2.4 and earlier, utilities that wanted to modify the time stamps of a file could copy the 4 date/time bytes from the global page into the SET_FILE_INFO parameter blocks. 

With 2.5 a conversion between the formats would be necessary, and any existing utilities would need modification. Similarly, an application that parsed the 2.4 date/time bytes for display would need to have a separate path for 2.5 global bytes. 

Perhaps 2.5's proposed global date time format should be reconsidered, and be clean superset of the file time stamp format, with just the additional sec/msec bytes?

(This is assuming the plans for the file timestamp format haven't changed to render this issue moot.)

**Comment by JohnMBrooks** [comment]
In ProDOS 2.5, no conversion should be needed since all dates are in the new extended format. P8 2.5 clock drivers return only new extended date/time in global page (and optionally also provide sec/msec), and the ProDOS 2.5 kernel automatically converts all legacy dates in a volume's file/dir entries to extended format in dram as the dir is read.

The only time a utility might deal with a legacy date is if the utility reads a disk volume at the block level, or has code to manually generate a legacy date.

-JB

**Comment by inexorabletash** [comment]
Okay - sounds like the format has changed since the KansasFest presentation a few years ago. Sorry for the noise.
